Repository thoth-station/package-releases-job, pull requests merged in 2018-04, with the labels that each got.

#4 build pipeline
  Jenkinsfile
Labels: approved

#7 Fix wrong report message
  app.py
Labels: approved

#8 humans: let's reclaim our mattermost channel
  Jenkinsfile
Labels: approved

#10 adding the OWNERS file
  OWNERS
Labels: approved

#9 Separate imagestreams
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M

#11 License and license header
  LICENSE
  app.py
Labels: approved, size/XL
