Repository thoth-station/package-releases-job, pull requests merged in 2018-07, with the labels that each got.

#33 added zuul config
  .coafile
  .travis.yml
  .zuul.yaml
  app.py
Labels: approved, size/M

#42 added a few more metrics
  CHANGELOG.md
  app.py
Labels: approved, size/M

#43 using f-strings for all logging
  Jenkinsfile
  app.py
Labels: approved, size/S

#40 Update cronJob-template.yaml
  openshift/cronJob-template.yaml
Labels: approved, size/S

#48 Pin down PyYaml due to aiogremlin version pinning
  Pipfile
Labels: approved

#50 Initial dependency lock
  Pipfile.lock
Labels: bot

#51 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#41 Update app.py
  app.py
Labels: size/XS

#53 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#54 fixed the configmap references
  openshift/cronJob-template.yaml
Labels: approved

#55 Report metrics submission to logs
  app.py
Labels: approved

#56 Automatic update of dependency thoth-storages from 0.0.33 to 0.1.0
  Pipfile.lock
Labels: bot

#58 Template labels
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#59 Automatic update of dependency thoth-storages from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#61 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot

#62 Automatic update of dependency prometheus-client from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot
