Repository thoth-station/package-releases-job, pull requests merged in 2018-06, with the labels that each got.

#25 set resource limits of BC, DC; relocked Pipfile
  CHANGELOG.md
  Jenkinsfile
  Pipfile.lock
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#26 Trigger build webhook for monitored packages
  Pipfile
  Pipfile.lock
  app.py
  config/thoth.yaml
Labels: approved, size/L

#30 Automatically trigger Kebechet build on Kebechet release
  config/thoth.yaml
Labels: approved, size/XS

#31 added yaml to coala glob, fixed template indentation
  .coafile
  Jenkinsfile
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#32 added a new metric
  CHANGELOG.md
  app.py
Labels: approved, size/S
