Repository thoth-station/package-releases-job, pull requests merged in 2018-08, with the labels that each got.

#65 Add metadata to job template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#66 Automatic update of dependency thoth-storages from 0.1.1 to 0.2.0
  Pipfile.lock
Labels: bot

#67 Automatic update of dependency thoth-storages from 0.2.0 to 0.3.0
  Pipfile.lock
Labels: bot

#68 Automatic update of dependency thoth-storages from 0.3.0 to 0.4.0
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency thoth-storages from 0.4.0 to 0.5.0
  Pipfile.lock
Labels: bot

#72 Automatic update of dependency thoth-storages from 0.5.0 to 0.5.1
  Pipfile.lock
Labels: bot

#73 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#74 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#76 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot

#71 Adjust to trigger TF builds automatically
  app.py
  config/thoth.yaml
Labels: approved, size/S
