Repository thoth-station/package-releases-job, pull requests merged in 2018-10, with the labels that each got.

#85 Automatic update of dependency click from 6.7 to 7.0
  Pipfile.lock
Labels: bot

#86 Automatic update of dependency thoth-common from 0.3.0 to 0.3.7
  Pipfile.lock
Labels: bot

#87 Automatic update of dependency prometheus-client from 0.3.1 to 0.4.1
  Pipfile.lock
Labels: bot

#88 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#89 Automatic update of dependency thoth-common from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#90 Automatic update of dependency thoth-common from 0.3.9 to 0.3.10
  Pipfile.lock
Labels: bot

#92 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency thoth-storages from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#96 Automatic update of dependency prometheus-client from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#98 reviewed logging messages
  .zuul.yaml
  app.py
Labels: approved, size/M, size/S

#100 Print version to logs
  app.py
Labels: approved, size/XS

#101 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#102 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#103 Automatic update of dependency thoth-storages from 0.5.4 to 0.6.0
  Pipfile.lock
Labels: bot

#105 Automatic update of dependency thoth-common from 0.3.12 to 0.3.14
  Pipfile.lock
Labels: bot

#109 Automatic update of dependency thoth-storages from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot
