Repository thoth-station/package-releases-job, pull requests merged in 2019-03, with the labels that each got.

#150 Report index against which the package update checks are done
  app.py
Labels: size/XS

#152 added image stream tag and namespace parameter
  .zuul.yaml
  openshift/cronJob-template.yaml
Labels: size/M, size/S

#154 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#156 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#157 Automatic update of dependency thoth-python from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#158 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot
