Repository thoth-station/package-releases-job, pull requests merged in 2019-10, with the labels that each got.

#247 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#245 Add untrahook to send package release notifications to
  config/thoth.yaml
Labels: approved, size/XS

#246 Enhace payload and package releases monitoring handling
  app.py
Labels: approved, size/S

#250 relocked dependencies to fix CVE-2017-18342
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/XL

#251 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#252 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#255 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#257 Update query functions according to new naming convention
  app.py
Labels: approved, size/XS

#261 Use normalized package names and package versions
  app.py
Labels: approved, size/XS

#262 Fix reversed return value in checks in release monitoring
  app.py
Labels: approved, size/XS

#264 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#265 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#266 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#267 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#268 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#269 Automatic update of dependency pre-commit from 1.18.3 to 1.19.0
  Pipfile.lock
Labels: bot

#270 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#271 Automatic update of dependency black from 19.3b0 to 19.10b0
  Pipfile.lock
Labels: bot

#272 Automatic update of dependency pre-commit from 1.19.0 to 1.20.0
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.14
  Pipfile.lock
Labels: bot
