Repository thoth-station/package-releases-job, pull requests merged in 2019-06, with the labels that each got.

#175 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#176 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#177 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#178 Update the trigger-build job to use the latest job API
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#179 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#180 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#181 Adjust requests and limits
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#182 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#184 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#183 Document local usage and some flags
  README.rst
Labels: approved, size/M

#185 Standardize environment variables and metrics
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/S

#186 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot
