Repository thoth-station/package-releases-job, pull requests merged in 2019-12, with the labels that each got.

#310 Automatic update of dependency pyyaml from 5.2b1 to 5.2
  Pipfile.lock
Labels: bot, size/M

#311 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/S

#312 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#313 Give package-releases job 2 hours to finish
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#314 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/S

#315 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/M

#316 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#317 Run package-releases-job twice a day
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#318 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot

#319 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/S

#321 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M

#322 Automatic update of dependency pyyaml from 5.2 to 5.3b1
  Pipfile.lock
Labels: bot, size/L
