Repository thoth-station/package-releases-job, pull requests merged in 2019-02, with the labels that each got.

#144 Update year in sources
  app.py
Labels: size/XS

#146 Automatic update of dependency thoth-storages from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#147 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#148 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#149 Check for new package releases daily by default
  openshift/cronJob-template.yaml
Labels: approved, size/XS
