Repository thoth-station/package-releases-job, pull requests merged in 2019-08, with the labels that each got.

#208 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#209 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#210 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#211 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#213 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#214 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#216 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#215 Add missing deployment name to template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#217 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#218 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#219 Added config
  .thoth.yaml
Labels: approved, size/S
