Repository thoth-station/package-releases-job, pull requests merged in 2019-09, with the labels that each got.

#221 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#223 Switch from Dgraph to PostgreSQL in deployment
  openshift/cronJob-template.yaml
Labels: approved, size/M

#224 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#225 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#226 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#227 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#228 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#229 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#230 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#231 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#232 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#236 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#237 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#235 State how to run against local deployment
  README.rst
Labels: approved, size/S

#242 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#243 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
