Repository thoth-station/package-releases-job, pull requests merged in 2019-11, with the labels that each got.

#278 Fix API Call Error
  app.py
Labels: approved, size/XS

#280 Stop using starting deadline seconds
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#282 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#284 use Prometheus collector Registry
  app.py
Labels: approved, size/M

#285 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#286 Automatic update of dependency thoth-python from 0.6.5 to 0.7.1
  Pipfile.lock
Labels: bot

#287 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#288 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#289 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#290 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/M

#291 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/S

#292 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/S

#293 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.22
  Pipfile.lock
Labels: bot, size/S

#294 Specify image stream registry in cronjob template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#295 Check for new releases more often
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#297 Use correct query to obtain Python package index configuration
  app.py
Labels: approved, size/XS

#298 Search only enabled Python indexes
  app.py
Labels: approved, size/XS

#299 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/M

#300 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#301 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#303 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/L

#305 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/M

#306 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#307 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M

#309 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M
