Repository thoth-station/package-releases-job, pull requests merged in 2019-05, with the labels that each got.

#166 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#167 Automatic update of dependency thoth-storages from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#168 Automatic update of dependency thoth-storages from 0.11.2 to 0.11.3
  Pipfile.lock
Labels: bot

#169 Automatic update of dependency thoth-storages from 0.11.3 to 0.11.4
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#170 fix template for openshift >=3.11
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#172 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: approved, bot

#174 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot
