Repository thoth-station/package-releases-job, pull requests merged in 2020-07, with the labels that each got.

#420 Add version to use release pipeline on quay
  app.py
Labels: approved, size/M

#422 include github issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved, size/M

#424 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#425 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#426 Automatic update of dependency thoth-common from 0.13.8 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#428 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot, size/L

#433 Release of version 0.6.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/L

#423 migrate manifest for the application to config app
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#434 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#435 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/L

#436 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#421 enable pre-commit support for the application
  .coafile
  .pre-commit-config.yaml
  .zuul.yaml
  CHANGELOG.md
  README.rst
  app.py
Labels: approved, size/XL
