Repository thoth-station/package-releases-job, pull requests merged in 2020-11, with the labels that each got.

#515 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot

#516 Automatic update of dependency thoth-common from 0.20.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/XL

#518 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/XL

#522 Add maintainers
  .thoth.yaml
Labels: approved, size/XS

#523 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/S

#525 port to python 38
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#526 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS
