Repository thoth-station/package-releases-job, pull requests merged in 2020-09, with the labels that each got.

#449 make package-release-job a producer
  .env.template
  Pipfile
  Pipfile.lock
  app.sh
  producer.py
  version.py
Labels: approved, size/XXL

#451 Add maintainer
  .thoth.yaml
Labels: approved, size/XS

#455 Release of version 0.7.0
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#456 Release of version 0.8.0
  CHANGELOG.md
  version.py
Labels: approved, bot, size/L

#457 run safely
  app.sh
Labels: approved

#459 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#460 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#461 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot

#463 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.2
  Pipfile.lock
Labels: approved, bot

#466 Release of version 0.8.1
  CHANGELOG.md
  version.py
Labels: approved, bot

#469 make app.sh executable
  app.sh
Labels: approved, size/XS

#470 enable aicoe-ci to build and deploy
  .aicoe-ci.yaml
Labels: size/S

#472 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/XS

#475 Release of version 0.8.2
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#476 fix import PackageReleasedMessage
  producer.py
Labels: approved, size/XS

#478 Automatic update of dependency thoth-messaging from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: approved, bot, size/XS

#480 Release of version 0.8.3
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#482 Manual update of dependency thoth-messaging from 0.7.3 to 0.7.6
  Pipfile.lock
Labels: approved, size/S

#485 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/M

#487 Release of version 0.8.4
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#489 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#490 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/L

#491 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/XS

#493 Be verbose
  producer.py
Labels: approved, size/XS

#495 Release of version 0.8.5
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#496 Send message only of packages that do not exist, not all.
  producer.py
Labels: approved, size/M

#499 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.7
  Pipfile.lock
Labels: approved, bot, size/M

#500 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#501 Release of version 0.8.6
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#502 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.12
  Pipfile.lock
Labels: approved, bot, size/XS

#503 Show logging and solve bug in package-release logic
  producer.py
Labels: approved, size/XS

#505 Automatic update of dependency thoth-storages from 0.25.12 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/XS

#507 Automatic update of dependency thoth-messaging from 0.7.7 to 0.7.8
  Pipfile.lock
Labels: approved, bot, size/XS

#509 Release of version 0.8.7
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S
