Repository thoth-station/package-releases-job, pull requests merged in 2020-03, with the labels that each got.

#377 Read package names from a JSON/YAML file
  Pipfile
  Pipfile.lock
  app.py
Labels: approved, size/XL

#378 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.4
  Pipfile.lock
Labels: bot, size/L

#379 Automatic update of dependency thoth-storages from 0.22.4 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#380 Automatic update of dependency pyyaml from 3.13 to 5.3.1
  Pipfile.lock
Labels: bot

#381 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/S

#382 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#383 Automatic update of dependency pyyaml from 5.3.1 to 3.13
  Pipfile.lock
Labels: bot, size/M

#384 Automatic update of dependency thoth-common from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/XS

#386 Automatic update of dependency thoth-common from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot, size/XS

#387 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#388 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/S

#389 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M
